### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by maximpetrov** [DanilaEremenko/Game#1]
Честно говоря я не совсем понял, зачем у Вас в репозитории четыре проекта, поэтому поверхностно посмотрел на все. Основное замечание - реализация и интерфейс у Вас тесно переплетены.

В идеале должен быть набор классов (реализация), которые реализую всю логику приложения, но ничего не знают об пользовательском интерфейсе. У этого набора классов должен быть программный интерфейс (набор методов), который позволять передавать ему управляющие воздействия от пользователя и получать всю нужную для пользователя информацию.
Второй набор классов, представляющих интерфейс, должен содержать минимум логики и в основном состоять из вызовов управляющих методов реализации по наступлению каких-то событий, в основном действий пользователя, и отрисовки интерфейса, информацию для которых он также получает из методов реализации.

**Comment by DanilaEremenko** [comment]
@maximpetrov основной проект все что c Panzer начинается, остальные можно не смотреть

**Comment by DanilaEremenko** [comment]
@maximpetrov по этому замечанию я понял, постараюсь переделать.
В дальнейшем проверяйте только классы Panzer,пожалуйста

**Comment by DanilaEremenko** [comment]
@maximpetrov логика реализована в классах Panzer,PanzerBullet,PanzerDirection и PanzerElement, а в классе PanzerGame мы только создаем объекты, добавляем их на панель и вызываем их методы при нажатии на клавиши. Логики там вроде как минимум, если я не ошибаюсь

**Comment by maximpetrov** [comment]
1. Я не спорю, что логика у Вас реализована в этих классах, но они же отвечают за отрисовку, то есть являются также интерфейсными.
1. Для проверки значения `enum` удобнее и стилистически правильнее использовать не цепочку `if ... else if ...`, а `switch ... case ...`
1. "Магические числа" тоже плохой стиль программирования.
1. Неплохо бы написать какие-нибудь тесты.

**Comment by DanilaEremenko** [comment]
@maximpetrov 
2. Для проверки значения enum теперь используется switch-case
3."Магические числа" выразил через характеристики танков
4.Тесты не знаю как писать, если честно. Может быть можно тут без них обойтись, если это все-таки игра с графическим интерфейсом, в которой все можно проверить походу игрового процесса.
5.Добавил [главное меню](https://github.com/DanilaEremenko/Game/blob/master/Code/src/Panzer/PanzerMenu.java)
6.Создал класс [Levels](https://github.com/DanilaEremenko/Game/blob/master/Code/src/Panzer/Levels.java), в котором в дальнейшем буду храниться уровни  включающие в себя препятствия и танки. Таким образом образом класс [PanzerGame](https://github.com/DanilaEremenko/Game/blob/master/Code/src/Panzer/PanzerGame.java) стал намного проще и меньше, а класс Levels в дальнейшем будет очень удобно использовать для создания уровней.
7.Ну и пара мелочей, вроде возможности менять масштаб

**Comment by maximpetrov** [comment]
1. [Тут](https://github.com/DanilaEremenko/Game/blob/master/Code/src/Panzer/PanzerGame.java#L48-L75) забыты в некоторых строчках `else`, а вообще это тоже `Enum`, так что опять же правильнее использовать `switch-case`.
1. Ваш подход к описанию уровней не совсем правильный. Лучше было бы хранить сами уровни в файлах в каком-нибудь формате, а в программе загружать их из этих файлов. Формат этих файлов скорее всего будет проще для "пользователя", чем написание уровня в виде программного кода, а главное позволит добавлять/изменять уровни без пересборки программы.

**Comment by DanilaEremenko** [comment]
@maximpetrov 
1.
Последние циклы if-else для управления танками [заменены](https://github.com/DanilaEremenko/Game/blob/master/Code/src/Panzer/PanzerGame.java#L50-L85) на swtich-case
Класс [Levels](https://github.com/DanilaEremenko/Game/blob/master/Code/src/Panzer/Levels.java) переделан через ArrayList  'Panzer'  panzers.
Также конструктор PanzerBullet теперь принимает Panzer и пули привязываются к танку, а
метод [move()](https://github.com/DanilaEremenko/Game/blob/master/Code/src/Panzer/PanzerBullet.java#L26) в классе PanzerBullet больше не принимает никаких аргументов,т.к. теперь
у пуль есть [поле танка](https://github.com/DanilaEremenko/Game/blob/master/Code/src/Panzer/PanzerBullet.java#L12), которому они принадлежат.
2.
Постараюсь переделать
Как вариант возможно это сделать через файл XML или лучше использовать какой-то другой способ?

**Comment by maximpetrov** [comment]
Можно использовать один из стандартных форматов (XML, JSON), можете придумать свой формат. Для работы со стандартными форматами есть готовые библиотеки, в которых правда нужно разобраться. Если использовать свой формат, то придётся разбирать файл самостоятельно, то он может быть проще, чем, например, XML, который выглядит достаточно громоздко, да и разбираться с библиотеками не придётся.

**Comment by DanilaEremenko** [comment]
@maximpetrov 
Можно реализовать это через абстрактный класс, который считывает условия из XML документа и исходя из этого генерирует карту?

**Comment by maximpetrov** [comment]
Не совсем уверен, что понял, что Вы подразумеваете под "реализовать через абстрактный класс". Можно сделать обычный класс, который в конструкторе принимать XML-файл, из него считывает информацию об уровне и заполняет свои поля.

По поводу формата XML файла. Во-первых, плохая идея хранить номер уровня в названии тега, это усложнит разбор это файла: Вам придётся заранее знать число уровней или хитро разбирать эти теги. Лучше сделать одинаковый тег и использовать атрибуты. Во-вторых, использовать перечисление через запятую, тоже не лучший стиль. Лучше разбить их на отдельные элементы, атрибутами которых сделать координаты.

**Comment by maximpetrov** [comment]
P.S. Если Вы не очень поняли, что я написал про формат XML, посмотрите PullRequest, который я Вам сделал.

**Comment by DanilaEremenko** [comment]
@maximpetrov 
Он здесь должен лежать?
![image](https://user-images.githubusercontent.com/25672140/27909513-a70db4d8-6259-11e7-87ae-084b65ac30e5.png)

**Comment by maximpetrov** [comment]
Похоже, я забыл нажать кнопку "Create PullRequest", теперь должен появиться.

**Comment by DanilaEremenko** [comment]
@maximpetrov Я кажется понял, что вы имели в виду под своим форматом. То есть уровни можно просто хранить в текстовых файлах со своей кодировкой,а в конструкторе Levels это все расшифровывать

**Comment by DanilaEremenko** [comment]
@maximpetrov 
1.Теперь информация об уровнях хранится в текстовых файлах 
Вот [1 уровень](https://github.com/DanilaEremenko/Game/blob/master/Code/src/LevelOne.txt)
2.Загружаются и хранятся уровни в классе [Levels](https://github.com/DanilaEremenko/Game/blob/master/Code/src/Panzer/Levels.java)
3.В классе [Game](https://github.com/DanilaEremenko/Game/blob/master/Code/src/Panzer/PanzerGame.java) теперь хранится только primaryStage

**Comment by maximpetrov** [comment]
Формат хранения уровня немного странный, но это Ваше дело. Мне не очень нравиться, что у Вас `Levels` полностью статический. Лучше было бы в результате разбора файла получать объект уровня, в котором хранились бы все его параметры, а не получать их через статические поля. Замечание про нежелательность использования статических полей только для того, чтобы получить доступ к хранящимся данным без передачи экземпляра класса, вообще относиться не только к классу `Levels`.

**Comment by DanilaEremenko** [comment]
@maximpetrov класс Levels пожалуй и правда стоит переделать,  но вот в других не уверен, что есть, что переделывать(касательно использования статических полей). В остальных классах вроде как только по несколько статических полей и методов, а в Классе PanzerElement статические методы заменяют конструкторы, поскольку их удобнее различать по названию

**Comment by maximpetrov** [comment]
Про `PanzerElement` речь не идёт, такие статические методы действительно используются, только, возможно, стоит сделать конструктор `PanzerElement` приватным, если предполагается создавать элементы только этими тремя методами и не предполагается создавать "вручную".

**Comment by DanilaEremenko** [comment]
@maximpetrov
1.Класс Levels больше не абстрактный 
2.У класса PanzerGame теперь есть поле myLevel
